Exercise list view update
rage/secret-project-331 pull request #1053
Opened 2022-12-12 17:15 UTC by Maijjay

2022-12-15 08:14 UTC, nygrenh requested changes

2022-12-15 08:14 UTC, nygrenh commented on services/main-frontend/src/components/page-specific/manage/courses/id/exercises/CourseExercises.tsx
> +          color: ${baseTheme.colors.gray["700"]};
Not a string

2022-12-15 08:14 UTC, nygrenh commented on services/main-frontend/src/components/page-specific/manage/courses/id/exercises/ExerciseList.tsx
> +                        // PAGE should be replaced with {t("page-number")}, once I know how
Outdated comment

2022-12-15 08:14 UTC, nygrenh commented on services/main-frontend/src/components/page-specific/manage/courses/id/exercises/ExerciseList.tsx
> +                              {exercise.count === null ? (
```
{exercise.count !== null && (<Link>..</Link>)}
```

2022-12-15 08:14 UTC, nygrenh commented on shared-module/src/locales/en/main-frontend.json
> +  "page-number": "PAGE {{page-number}}",
Write with normal case, and use `text-transform: uppercase` in the component where this is used.

2022-12-22 08:32 UTC, d471061c approved these changes

2023-01-02 09:04 UTC, nygrenh approved these changes

2023-01-02 09:05 UTC, merged