playground-views websocket
rage/secret-project-331 pull request #1083
Opened 2023-02-27 09:59 UTC by Heliozoa

2023-02-27 10:43 UTC, Heliozoa commented on services/main-frontend/src/pages/playground-views.tsx
> +      console.log("ws message", ev)
delete

2023-02-27 10:45 UTC, nygrenh requested changes

2023-02-27 10:45 UTC, nygrenh commented on kubernetes/base/kustomization.yaml
> +  - tmc-service-account.yml
Keep this as it is

2023-02-27 10:45 UTC, nygrenh commented on services/main-frontend/src/pages/playground-views.tsx
> +          grading_update_url: `http://project-331.local/api/v0/main-frontend/playground-views/grading/${websocketId}`,
Make this work in production. Maybe env var for base url

2023-02-27 10:45 UTC, nygrenh commented on services/main-frontend/src/pages/playground-views.tsx
> +      } else if (param.type === "fromWebsocket") {
Set data for the mutation directly instead of mutating the mutation

2023-03-01 11:11 UTC, nygrenh requested changes

2023-03-01 11:11 UTC, nygrenh commented on services/main-frontend/Dockerfile.production.cache.dockerfile
> +ENV NEXT_PUBLIC_PUBLIC_ADDRESS="https://courses.mooc.fi"
Use kubernetes configs and this: https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration

2023-03-06 10:07 UTC, nygrenh requested changes

2023-03-06 10:07 UTC, nygrenh commented on kubernetes/base/main-frontend/deployment.yml
> +              value: "https://courses.mooc.fi"
http://project-331.local here and patch only production

2023-03-18 18:00 UTC, merged