Change course language
rage/secret-project-331 pull request #1087
Opened 2023-03-08 15:58 UTC by Maijjay

![Screenshot from 2023-03-08 17-56-10](https://user-images.githubusercontent.com/51128208/223763581-cd9940a9-05ec-4fdb-a0ae-abc54474e94d.png)
![Screenshot from 2023-03-08 17-56-49](https://user-images.githubusercontent.com/51128208/223763651-875f0741-4109-4bdb-91d7-ddeb7c65cdb6.png)

2023-03-13 11:22 UTC, george-misan commented
Everything looks fine, But I think they should be a border around the flag icon (as depicted in the image below) because the Finland flag looks weird with no border. I will suggest using 2px of border width and color: baseTheme.colors.grey[200]
![image](https://user-images.githubusercontent.com/57463554/224687379-013c617c-cce1-40af-9a9a-bacb0816f1b1.png)

2023-03-15 10:03 UTC, Maijjay commented
Here are the borders for the flags:
![Screenshot from 2023-03-14 22-48-12](https://user-images.githubusercontent.com/51128208/225274795-27d8f657-cb90-4a31-b94b-865ca91bf0fb.png)
![Screenshot from 2023-03-14 22-48-03](https://user-images.githubusercontent.com/51128208/225274800-5778e3d0-bcef-4da4-949d-695775d22e3f.png)

2023-03-15 12:01 UTC, nygrenh requested changes

2023-04-19 10:16 UTC, nygrenh requested changes

2023-04-19 10:16 UTC, nygrenh commented on services/headless-lms/server/src/controllers/course_material/courses.rs
> +#[generated_doc]
Add a documentation commment for endpoint path like in line 625

2023-04-19 10:16 UTC, nygrenh commented on services/headless-lms/server/src/controllers/course_material/courses.rs
> +            "/{course_id}/pages/{page_language_group_id}",
```suggestion
            "/{course_id}/pages/by-language-group-id/{page_language_group_id}",
```

2023-04-19 10:16 UTC, nygrenh commented on services/headless-lms/models/src/pages.rs
> +    AND p.page_language_group_id = $2
AND deleted_at is NULL

2023-04-24 11:05 UTC, nygrenh requested changes

2023-04-24 11:05 UTC, nygrenh commented on services/headless-lms/server/src/controllers/course_material/courses.rs
> +#[generated_doc]
Also one sentence here

2023-04-26 10:05 UTC, nygrenh requested changes
Does this advertise a language if the language course is still a draft?

2023-04-28 12:34 UTC, merged