Export exercise submissions
rage/secret-project-331 pull request #1103
Opened 2023-04-12 08:32 UTC by anadis504

2023-04-12 10:45 UTC, nygrenh requested changes

2023-04-12 10:45 UTC, nygrenh commented on services/headless-lms/server/src/controllers/main_frontend/courses.rs
> +        Act::Edit, // Teach  or Edit or Download maybe ??
teach

2023-04-12 10:45 UTC, nygrenh commented on services/main-frontend/src/components/page-specific/manage/courses/id/index/ManageCourse.tsx
> +      <ul
OnlyRenderIfPermissions

2023-04-12 11:01 UTC, Heliozoa requested changes

2023-04-17 11:07 UTC, nygrenh requested changes

2023-04-18 09:40 UTC, nygrenh approved these changes

2023-04-18 09:41 UTC, merged