Edit proposal for deleted block handling
rage/secret-project-331 pull request #1120
Opened 2023-05-17 09:55 UTC by Maijjay

![Screenshot from 2023-05-17 12-31-58](https://github.com/rage/secret-project-331/assets/51128208/6a4999cd-1363-4f33-b017-8e940713819a)

2023-05-22 10:42 UTC, Maijjay commented
![Screenshot from 2023-05-22 13-28-21](https://github.com/rage/secret-project-331/assets/51128208/a2f0bd89-db7f-47ea-97ae-8cb934a9b96b)
@george-misan

2023-05-22 11:16 UTC, nygrenh requested changes

2023-05-22 11:16 UTC, nygrenh commented on services/headless-lms/models/src/proposed_page_edits.rs
> +        } else {
If we swapped the else and if branches, we could get rid of the unwrap

```rust
if let Some(block) = block {
// contents of the else branch
} else {
// contents of the if branch
}
```

2023-05-24 10:10 UTC, nygrenh approved these changes

2023-05-24 10:10 UTC, merged