Layout blocks
rage/secret-project-331 pull request #117
Opened 2021-06-22 03:52 UTC by george-misan

2021-07-12 07:34 UTC, nygrenh requested changes

2021-07-12 07:34 UTC, nygrenh commented on services/course-material/src/components/ContentRenderer/index.tsx
> +=======
merge conflict

2021-07-12 07:34 UTC, nygrenh commented on shared-module/package.json
> +    "styled-components": "^5.3.0",
no styled components

2021-07-14 07:40 UTC, nygrenh requested changes
+ merge conflict in shared-module

2021-07-14 07:40 UTC, nygrenh commented on services/course-material/src/components/ContentRenderer/AudioBlock.tsx
> +export default AudioBlock
```suggestion
export default withErrorBoundary(AudioBlock)
```

2021-07-14 07:40 UTC, nygrenh commented on services/course-material/src/components/ContentRenderer/AudioBlock.tsx
>  import { normalWidthCenteredComponentStyles } from "../../styles/componentStyles"
```suggestion
import withErrorBoundary from "../../shared-module/utils/withErrorBoundary"
import { normalWidthCenteredComponentStyles } from "../../styles/componentStyles"
```

2021-07-15 10:29 UTC, jolampi approved these changes

2021-07-15 10:37 UTC, merged