Expandable content -block
rage/secret-project-331 pull request #1305
Opened 2024-09-02 15:48 UTC by Maijjay

2024-10-10 11:09 UTC, george-misan approved these changes

2024-10-15 07:28 UTC, nygrenh requested changes
Lock the main blocks and add `templateLock={false}` to the inner inner blocks.

2024-10-15 07:28 UTC, nygrenh commented on services/course-material/src/components/ContentRenderer/moocfi/FlipCard/FlipCardBlock.tsx
> +              throw new Error("Function not implemented.")
Check out if this crashes the frontend

2024-10-15 07:28 UTC, nygrenh commented on services/course-material/src/components/ContentRenderer/moocfi/FlipCard/InnerCardBlock.tsx
> +  if (isBlockImage(props.data.innerBlocks[0]) && props.data.innerBlocks.length == 1) {
Add a comment for explaining the if

2024-10-15 07:28 UTC, nygrenh commented on services/course-material/src/components/ContentRenderer/moocfi/FlipCard/InnerCardBlock.tsx
> +  if (isBlockImage(props.data.innerBlocks[0]) && props.data.innerBlocks.length == 1) {
Does it crash if innerblocks is empty?

2024-10-15 07:28 UTC, nygrenh commented on services/course-material/src/components/ContentRenderer/moocfi/FlipCard/FlipCardBlock.tsx
> +          ${currentIsImage ? "" : "border: 3px solid #bfbec6"};
```suggestion
          ${!currentIsImage && "border: 3px solid #bfbec6;"}
```

2024-10-15 07:28 UTC, nygrenh commented on services/course-material/src/components/ContentRenderer/moocfi/FlipCard/FlipCardBlock.tsx
> +  let size = 0
create a function in this file sizeStringToSizePx

2024-10-15 07:28 UTC, nygrenh commented on services/course-material/src/components/ContentRenderer/moocfi/FlipCard/FlipCardBlock.tsx
> +
Check if frontCard and backcard are defined and return an error banner if they are not.

2024-10-15 07:28 UTC, nygrenh commented on services/cms/src/components/blocks/FlipCardSizeCustomizer.tsx
> +/* eslint-disable i18next/no-literal-string */
Don't need to ignore the whole file

2024-10-17 07:09 UTC, nygrenh approved these changes

2024-10-17 07:09 UTC, merged