Document all columns in the database
rage/secret-project-331 pull request #211
Opened 2021-07-14 06:26 UTC by nygrenh

2021-07-14 07:18 UTC, Heliozoa requested changes

2021-07-14 07:21 UTC, nygrenh commented on services/headless-lms/migrations/20210713050637_add_comments_to_columns.up.sql
> +COMMENT ON COLUMN users.upstream_id IS 'User''s id in upstream system (currently TMC). Only used to interact with the upstream authentication system. Internally the preferred identifier is user.id.';
```suggestion
COMMENT ON COLUMN users.upstream_id IS 'User''s id in upstream system (currently TMC). Only used to interact with the upstream authentication system. Internally the preferred identifier is user.id.';
COMMENT ON COLUMN users.email IS 'Email address where the student can be reached. Can change, don''t use this as an identifier.';
```

2021-07-15 07:05 UTC, george-misan requested changes

2021-07-15 07:13 UTC, nygrenh commented on services/headless-lms/migrations/20210713050637_add_comments_to_columns.up.sql
> +COMMENT ON COLUMN exercise_tasks.private_spec IS 'Fully defines an exercise task: tells how the exercise is structured and how it should be checked for correctness. All other specs can be derived fro
Defines an exercise task fully

2021-07-15 07:14 UTC, nygrenh commented on services/headless-lms/migrations/20210713050637_add_comments_to_columns.up.sql
> +COMMENT ON COLUMN gradings.submission_id IS 'The submission that this grading grades.';
The submission being graded

2021-07-15 07:16 UTC, nygrenh commented on services/headless-lms/migrations/20210713050637_add_comments_to_columns.up.sql
> +COMMENT ON COLUMN gradings.score_given IS 'How many points were given from in this grading. This has been scaled to the max point that are specified in the exercise editor.';
How many points were given in this grading. This has been scaled to the max points of the exercise.

2021-07-15 07:17 UTC, nygrenh commented on services/headless-lms/migrations/20210713050637_add_comments_to_columns.up.sql
> +COMMENT ON COLUMN gradings.unscaled_max_points IS 'Score maximum we got from exercise service when doing to grading. This has not been adjusted to the max score that was specified in the exercise edi
Score maximum we got from the exercise service when doing the grading. This has not been adjusted to the max score is specified in the exercise.

2021-07-15 07:18 UTC, nygrenh commented on services/headless-lms/migrations/20210713050637_add_comments_to_columns.up.sql
> +COMMENT ON COLUMN gradings.unscaled_score_maximum IS 'How many points exercise service wanted to give from this exercise. This has not been adjusted to the max score that was specified in the exercis
How many points the exercise service wanted to give from this exercise. This has not been adjusted to the max score that was specified in the exercise.

2021-07-15 07:21 UTC, nygrenh commented on services/headless-lms/migrations/20210713050637_add_comments_to_columns.up.sql
> +COMMENT ON COLUMN regrading_submissions.regrading_id IS 'The regrading operation where the submission specified in submission_id belongs to.';
The regrading operation to which the submission is attached to.

2021-07-15 07:22 UTC, nygrenh commented on services/headless-lms/migrations/20210713050637_add_comments_to_columns.up.sql
> +COMMENT ON COLUMN users.upstream_id IS 'User''s id in upstream system (currently TMC). Only used to interact with the upstream authentication system. Internally the preferred identifier is user.id.';
User''s id in upstream system (currently TMC). It is used to interact with the upstream authentication system. Internally the preferred identifier is user.id.'

2021-07-15 07:29 UTC, nygrenh commented on services/headless-lms/migrations/20210713050637_add_comments_to_columns.up.sql
> +COMMENT ON COLUMN user_exercise_states.selected_exercise_task_id IS 'If an exercise has multiple possible exercise tasks and we''re students a random exercise task, we save the given exercise task he
If an exercise has multiple possible exercise tasks and we are giving each student a random exercise task, we save the given exercise task here. This is used for giving the same task back if the user reloads the page. Also, it is also used for checking during submission to ensure the user can not post an answer to a task that has not been given to them.

2021-07-15 07:31 UTC, nygrenh commented on services/headless-lms/migrations/20210713050637_add_comments_to_columns.up.sql
> +COMMENT ON COLUMN email_templates.content IS 'Content of the email in an abstract form. Same structure for the data as in pages.content but the allowed blocks here is limited. The html and plain text
Uses the same structure for the data as pages.content but the allowed blocks here is limited

2021-07-16 06:01 UTC, merged