Course material pre commit hook
rage/secret-project-331 pull request #230
Opened 2021-07-16 10:43 UTC by HegePI

2021-07-19 07:38 UTC, nygrenh requested changes

2021-07-19 07:38 UTC, nygrenh commented on services/course-material/src/components/ContentRenderer/CoverBlock.tsx
> +// const ImageContainer = styled.div`
remove

2021-07-19 07:38 UTC, nygrenh commented on services/course-material/package.json
> +    "@fortawesome/react-fontawesome": "^0.1.14",
these are good but others are not

2021-07-19 09:46 UTC, HegePI commented on services/course-material/src/components/ContentRenderer/CoverBlock.tsx
> +// const ImageContainer = styled.div`
removed

2021-07-20 07:52 UTC, nygrenh approved these changes

2021-07-20 08:18 UTC, merged