Gutenberg: don't crash on unsupported block types, instead replace with unsupported block placeholder block
rage/secret-project-331 pull request #265
Opened 2021-07-26 07:13 UTC by iPegii

Create unsupported block, add handling

2021-07-26 07:27 UTC, nygrenh requested changes

2021-07-26 07:27 UTC, nygrenh commented on services/cms/src/blocks/UnsupportedBlock/index.tsx
> +const UnsupportedConfiguration: BlockConfiguration = {
```suggestion
const UnsupportedBlock: BlockConfiguration = {
```

2021-07-26 07:27 UTC, nygrenh commented on services/cms/src/blocks/UnsupportedBlock/index.tsx
> +export default UnsupportedConfiguration
```suggestion
export default UnsupportedBlock
```

2021-07-26 07:27 UTC, nygrenh commented on services/cms/src/blocks/UnsupportedBlock/UnsupportedEditor.tsx
> +const ALLOWED_NESTED_BLOCKS = [""]
```suggestion
```

2021-07-26 07:27 UTC, nygrenh commented on services/cms/src/blocks/UnsupportedBlock/UnsupportedEditor.tsx
> +      <InnerBlocks allowedBlocks={ALLOWED_NESTED_BLOCKS} />
```suggestion
```

2021-07-26 07:27 UTC, nygrenh commented on services/cms/src/components/editors/PageEditor.tsx
> +    const resContent: BlockInstance[] = res.content as BlockInstance[]
before handlesave

2021-07-26 07:27 UTC, nygrenh commented on services/cms/src/components/editors/GutenbergEditor.tsx
> +    const modfiedNewContent = newContent.map((block) => {
do this in this component/in the parent of this component before we pass the content to BlockEditorProvider

2021-07-27 07:18 UTC, nygrenh requested changes

2021-07-27 07:18 UTC, nygrenh commented on services/cms/src/components/editors/PageEditor.tsx
> +  useEffect(() => {
https://reactjs.org/docs/hooks-reference.html#usememo

2021-07-27 07:18 UTC, nygrenh commented on services/cms/src/components/editors/PageEditor.tsx
> +    const allSupportedBlocks = supportedCoreBlocks.concat(
check if top level page from page.chapter_id and select which one to use

2021-07-29 07:49 UTC, nygrenh requested changes
Also implement in email editor

2021-07-29 07:49 UTC, nygrenh commented on services/cms/src/components/editors/PageEditor.tsx
> +  const allSupportedBlocks = urlPath.startsWith("/chapter-1/")
```suggestion
  const allSupportedBlocks = data.chapter_id
```

2021-07-30 13:19 UTC, nygrenh requested changes

2021-08-03 08:17 UTC, nygrenh requested changes

2021-08-03 08:17 UTC, nygrenh commented on services/cms/src/utils/Gutenberg/UseBlocksWithUnsupportedBlocksRemoved.ts
> +export function UseBlocksWithUnsupportedBlocksRemoved(
```suggestion
export function useBlocksWithUnsupportedBlocksRemoved(
```
Also rename the file

2021-08-03 08:17 UTC, nygrenh commented on services/cms/src/components/editors/PageEditor.tsx
>    useMemo(() => {
Move useMemo to the hook.

```js
    const contentWIthUsupportedBlocksRemoved =  useBlocksWithUnsupportedBlocksRemoved(content, allSupportedBlocks)
```

2021-08-03 08:17 UTC, nygrenh commented on services/cms/src/utils/Gutenberg/UseBlocksWithUnsupportedBlocksRemoved.ts
> +  const modifiedBlocks = blocks.map((block) => {
react.memo

2021-08-05 07:12 UTC, nygrenh requested changes

2021-08-05 07:12 UTC, nygrenh commented on services/cms/src/utils/Gutenberg/useBlocksWithUnsupportedBlocksRemoved.ts
> +export default function useBlocksWithUnsupportedBlocksRemoved(
remove the dead code

2021-08-06 08:10 UTC, nygrenh requested changes

2021-08-06 08:10 UTC, nygrenh commented on services/cms/src/components/editors/PageEditor.tsx
>    const [content, setContent] = useState<BlockInstance[]>(data.content as BlockInstance[])
const [content, setContent] = useState<BlockInstance[]>(modifyBlocks(data.content) as BlockInstance[])

2021-08-10 07:13 UTC, nygrenh requested changes

2021-08-10 07:13 UTC, nygrenh commented on services/cms/src/utils/Gutenberg/modifyBlocks.ts
> +/*import { useMemo } from "react"
dead code

2021-08-10 07:46 UTC, sebazai approved these changes

2021-08-10 07:50 UTC, merged