Move _app.tsx to shared module
rage/secret-project-331 pull request #284
Opened 2021-08-02 13:35 UTC by iPegii

2021-08-04 07:49 UTC, nygrenh requested changes
https://github.com/rage/secret-project-331/blob/master/services/main-frontend/src/pages/index.tsx

2021-08-10 07:09 UTC, nygrenh requested changes

2021-08-10 07:09 UTC, nygrenh commented on shared-module/package.json
> +    "recoil": "^0.4.0",
no

2021-08-10 07:09 UTC, nygrenh commented on services/example-exercise/package.json
> +    "recoil": "^0.4.0",
no

2021-08-10 07:45 UTC, sebazai approved these changes

2021-08-10 07:49 UTC, merged