bin/copy-and-check-shared-module
rage/secret-project-331 pull request #285
Opened 2021-08-02 14:38 UTC by iPegii

2021-08-03 08:41 UTC, nygrenh requested changes

2021-08-03 08:41 UTC, nygrenh commented on bin/copy-and-check-shared-module
> +run_command npx concurrently -n "cms,course-material,main-frontend,example-exercise" -c "green.bold,red.bold,blue.bold,yellow.bold" "npx tsc -p services/cms/ --noEmit" "npx tsc -p services/course-mat
```suggestion
run_command "$(dirname "$0")/tsc-check-all"
```

2021-08-10 07:10 UTC, nygrenh requested changes

2021-08-10 07:10 UTC, nygrenh commented on services/example-exercise/package.json
> +    "recoil": "^0.4.0",
no

2021-08-10 07:44 UTC, sebazai approved these changes

2021-08-10 07:48 UTC, merged