New CMS Blocks & Styling enhancements
rage/secret-project-331 pull request #294
Opened 2021-08-05 12:31 UTC by sebazai

2021-08-05 12:31 UTC, sebazai commented on services/cms/src/blocks/BlockWrapper.tsx
> + * Wrapper for edible blocks.
**yummy**

2021-08-05 12:34 UTC, sebazai commented on shared-module/src/styles/componentStyles.ts
> -  width: 100%;
This causes issues with CMS justify center. i.e.
https://github.com/rage/secret-project-331/pull/294/files#diff-466d275516a10e001cafe8f4b266d13c5fbbddf8ff0fff84d85276357bf044b9R13

Removing this does not affect anything, as max-width > width and on exercises we unset the max-width thus they'll default to full width from parents.

2021-08-05 12:35 UTC, sebazai commented on services/cms/src/styles/Gutenberg/editor-styles.scss
> -  font-size: $editor-font-size;
This probably caused the mismatch on latex snapshot e2e tests.

2021-08-05 12:35 UTC, sebazai commented on services/cms/src/styles/Gutenberg/style.scss
> - * Animations
These are unnecessary as we don't use the edit-post wordpress package.

2021-08-05 12:42 UTC, sebazai commented on services/cms/src/blocks/HeroSection/HeroSectionEditor.tsx
> +    "core/buttons",
core/button deprecated, so if we want one button we still should use core/buttons with innerblocks.

2021-08-09 06:42 UTC, sebazai commented on services/cms/src/blocks/HeroSection/HeroSectionEditor.tsx
> +    "core/buttons",
Hardcoded button to use shared-module primary button

2021-08-09 07:44 UTC, nygrenh requested changes
LandingPageHeroSection on landing page, HeroSection on other pages

2021-08-09 07:44 UTC, nygrenh commented on services/cms/src/blocks/ChapterHeroSection/ChapterHeroSectionEditor.tsx
> +      <InnerBlocks template={CHAPTER_HERO_SECTION_TEMPLATE} allowedBlocks={ALLOWED_NESTED_BLOCKS} />
richtext

2021-08-09 07:44 UTC, nygrenh commented on services/cms/src/blocks/CourseObjectiveSection/CourseObjectiveSectionEditor.tsx
> +  ["core/heading", { content: "In this course you'll...", level: 2, textAlign: "center" }],
RichText

2021-08-09 07:44 UTC, nygrenh commented on services/cms/src/blocks/HeroSection/HeroSectionEditor.tsx
> +        onChange={(value: string) => setAttributes({ heroHeading: value })}
```suggestion
        onChange={(value: string) => setAttributes({ title: value })}
```

2021-08-09 07:44 UTC, nygrenh commented on services/cms/src/blocks/HeroSection/index.tsx
> +    heroHeading: {
```suggestion
    title: {
```

2021-08-09 07:44 UTC, nygrenh commented on services/cms/src/components/editors/GutenbergEditor.tsx
> -        }
Move these to line 175

2021-08-09 07:44 UTC, nygrenh commented on services/cms/tsconfig.json
> +  "include": ["next-env.d.ts", "additional.d.ts", "**/*.ts", "**/*.tsx"],
Remove

2021-08-09 07:44 UTC, nygrenh commented on services/course-material/tsconfig.json
> +  "include": ["next-env.d.ts", "additional.d.ts", "katex.d.ts", "**/*.ts", "**/*.tsx"]
Remove

2021-08-09 07:44 UTC, nygrenh commented on services/example-exercise/tsconfig.json
> +  "include": ["next-env.d.ts", "additional.d.ts", "**/*.ts", "**/*.tsx"]
Remove

2021-08-09 07:44 UTC, nygrenh commented on services/headless-lms/src/bin/seed.rs
> +            GutenbergBlock::empty_block_from_name("moocfi/course-objective-section".to_string()),
Set the columns inner blocks

2021-08-09 07:44 UTC, nygrenh commented on services/main-frontend/tsconfig.json
> +  "include": ["next-env.d.ts", "additional.d.ts", "**/*.ts", "**/*.tsx"],
remove

2021-08-09 10:44 UTC, nygrenh approved these changes

2021-08-09 10:44 UTC, merged