Handle errors when saving in editor
rage/secret-project-331 pull request #315
Opened 2021-08-16 11:59 UTC by jolampi

Fixes #266

2021-08-16 12:13 UTC, sebazai approved these changes

2021-08-17 07:39 UTC, nygrenh requested changes

2021-08-17 07:39 UTC, nygrenh commented on services/cms/src/components/editors/EmailEditor.tsx
> +  const [error, setError] = useState("")
```suggestion
  const [error, setError] = useState<string | null>(null)
```

2021-08-17 09:17 UTC, nygrenh approved these changes

2021-08-17 09:17 UTC, merged