courses content search language
rage/secret-project-331 pull request #575
Opened 2022-02-01 14:26 UTC by HegePI

2022-02-03 13:16 UTC, nygrenh requested changes

2022-02-03 13:16 UTC, nygrenh commented on services/headless-lms/utils/src/language_tag_to_name.rs
> +pub static LANGUAGE_TAG_TO_NAME: Lazy<HashMap<&str, &str>> = Lazy::new(|| {
```rust
let solar_distance = HashMap::from([
    ("Mercury", 0.4),
    ("Venus", 0.7),
    ("Earth", 1.0),
    ("Mars", 1.5),
]);
```

2022-02-04 06:21 UTC, HegePI commented on services/headless-lms/utils/src/language_tag_to_name.rs
> +pub static LANGUAGE_TAG_TO_NAME: Lazy<HashMap<&str, &str>> = Lazy::new(|| {
hashmap from

2022-02-04 12:26 UTC, nygrenh approved these changes

2022-02-04 12:26 UTC, merged