display deadline on exercise
rage/secret-project-331 pull request #711
Opened 2022-03-30 09:51 UTC by HegePI

2022-03-31 11:45 UTC, nygrenh requested changes

2022-03-31 11:45 UTC, nygrenh commented on services/headless-lms/server/src/controllers/course_material/exercises.rs
> +        if Utc::now() >= deadline {
1 second grace time to account clock drift.

Take the deadline by default from chapter and let exercise.deadline to override it.

2022-04-04 11:35 UTC, nygrenh requested changes

2022-04-04 11:35 UTC, nygrenh commented on services/headless-lms/server/src/controllers/course_material/exercises.rs
> +    let chapter = models::chapters::get_chapter(&mut conn, exercise.chapter_id.unwrap()).await?;
```rust
let course: OptionFuture<_> = exercise.chapter_id.map(|id| models::chapters::get_chapter(&mut conn, id))
.into(); 
```

2022-04-07 11:12 UTC, nygrenh requested changes

2022-04-07 11:12 UTC, nygrenh commented on services/headless-lms/server/src/controllers/course_material/exercises.rs
> +    // Exercise deadlines takes precedence to chapter deadlines
```rust
if let Some(deadline) = exercise.deadline.or(chapter.and_then(|c| c.deadline)) {} 
```

2022-04-07 11:27 UTC, nygrenh requested changes
Make the notification smaller and take the new design from figma

2022-04-07 11:36 UTC, HegePI commented on services/headless-lms/server/src/controllers/course_material/exercises.rs
> +    // Exercise deadlines takes precedence to chapter deadlines
```rust
if let Some(deadline) = exercise.deadline.or(chapter.and_then(|c| c.deadline)) {}
```
replaced with
```rust
    if let Some(deadline) = exercise
        .deadline
        .or_else(|| chapter.and_then(|c| c.deadline))
```
clippy suggestion

2022-04-11 11:50 UTC, nygrenh requested changes
`${ new Date().toLocaleString("fi", {dateStyle: "long", timeStyle: "short"})} (UTC${-(new Date().getTimezoneOffset() / 60).toString().replace(".", ":")})`

needs to look like this:

 "11. huhtikuuta 2022 klo 14.49 (UTC+03:00)"

```
  const { t, i18n } = useTranslation()
  const lang = i18n.language
```

2022-04-14 10:35 UTC, nygrenh approved these changes

2022-04-14 10:35 UTC, merged