Enforce authorization checks
rage/secret-project-331 pull request #783
Opened 2022-05-19 11:18 UTC by iPegii

2022-05-19 12:59 UTC, nygrenh requested changes

2022-05-19 12:59 UTC, nygrenh commented on services/headless-lms/server/src/controllers/main_frontend/course_instances.rs
>      let (sender, receiver) = tokio::sync::mpsc::unbounded_channel::<ControllerResult<Bytes>>();
```suggestion
    let (sender, receiver) = tokio::sync::mpsc::unbounded_channel::<BypassAuthorizationCheckResult<Bytes>>();
```

2022-05-19 12:59 UTC, nygrenh commented on services/headless-lms/server/src/controllers/main_frontend/users.rs
> +    token.0.ok(web::Json(user))
token.to_authorized_result(web::Json(user))

2022-06-09 07:30 UTC, nygrenh requested changes
Document the new functions/structs.
Write an example to the authorize, and skip_authorize documentation

2022-06-10 07:31 UTC, nygrenh requested changes

2022-06-10 07:31 UTC, nygrenh commented on services/headless-lms/server/src/domain/authorization.rs
> +/// token.authorized_ok(web::Json(cms_page_info))
The authorization token is the only way to return a controller result, and should only be used in controller functions that return a response to the user.

2022-06-10 07:31 UTC, nygrenh commented on services/headless-lms/server/src/domain/csv_export.rs
> +/// Takes UnboundedReceiverStream-stream with AuthorizedResponse and returns UnboundedReceiverStream-stream with only Bytes
Without this one, actix cannot stream our authorized streams as responses

also maybe an example

2022-06-14 08:17 UTC, jolampi approved these changes

2022-06-14 11:35 UTC, nygrenh approved these changes

2022-06-14 12:04 UTC, merged