quizzes checkbox submission view
rage/secret-project-331 pull request #801
Opened 2022-06-02 08:30 UTC by HegePI

2022-06-03 15:22 UTC, george-misan commented
Hello Heikki, the `public_quiz_item.options` of Checkbox is an empty array in the SubmissionComponent view; so there is no data to be displayed apart from the title in the submission view.

2022-06-06 08:02 UTC, nygrenh requested changes

2022-06-07 07:30 UTC, nygrenh requested changes

2022-06-07 07:30 UTC, nygrenh commented on services/quizzes/src/components/SubmissionComponents/Checkbox.tsx
> +  const correct = user_quiz_item_answer.intData === 1
```suggestion
  const checked = user_quiz_item_answer.intData === 1
```
Everything is correct

2022-06-08 07:17 UTC, nygrenh approved these changes

2022-06-08 07:17 UTC, merged